### ISSUE TITLE
Doc Issues/Typos

### ISSUE THREAD

**Issue by michael-hawker** [pwa-builder/documentation#4]
- [ ] Typo in 'Service' on FAQ
- [ ] Inconsistent Capitalization for Quick Start Polyfills

![image](https://user-images.githubusercontent.com/24302614/31646238-8651fd06-b2b5-11e7-8adc-cdbf516cb691.png)

- [ ] Strange encoding/extra characters in 's across page on http://docs.pwabuilder.com/benefits/benefits-windows-10/ (viewing in Edge)

![image](https://user-images.githubusercontent.com/24302614/31646222-701cf46e-b2b5-11e7-992d-ac5f51c92294.png)

**Comment by boyofgreen** [comment]
Thanks @michael-hawker  it was just a case of conjunction-ites . Those darn curly quotes and apostrophes

**Comment by boyofgreen** [comment]
fixed in next push
