### ISSUE TITLE
pwabuilder.com wrong SSL certifcate

### ISSUE THREAD

**Issue by bgadrian** [pwa-builder/documentation#7]
Hello,

I just wanted to let you know that the certificate for https://docs.pwabuilder.com/ is wrong
![image](https://user-images.githubusercontent.com/830001/36143123-dd82b84e-10b2-11e8-9f07-86385222ce35.png)
And https://pwabuilder.com is not working for me (timeout)

**Comment by boyofgreen** [comment]
Thanks,  I added the proper cert to the site.  As for the https redirect without www, I have a request in to our DNS for that.
Thanks!
Jeff
